#!/usr/bin/env python3
# origin: lemoncloud-io/knowledge@8480503:projects/second-brain/config/scripts/generate_raw_index.py
"""Generate the raw/ preservation index.

Run from the vault root. Regenerated by the vault-lint pass; the outputs are
never hand-edited. Contract: docs/raw-layout.md § 색인.

Outputs
- docs/raw-index.yml      machine-readable record of every git-tracked raw/*.md
                          (added date, source, derived-note refs) — the canonical index
- docs/raw-index.md       short human summary: counts, orphans, duplicate source URLs,
                          pointer to the .yml. No per-file listing.
- private/raw-index.yml   entries for raw/*.md that git does not track on this machine
                          (personal/local files). private/ is gitignored, so this never
                          reaches the shared vault. Written only when such files exist;
                          a stale copy is removed when they are gone.

Reads raw/ filenames + frontmatter only; never modifies anything under raw/.
Stdlib only (YAML is emitted by hand; JSON string quoting is valid YAML).
"""

import datetime
import glob
import json
import os
import re
import subprocess
import sys
import unicodedata

SCAN_GLOBS = ["wiki/**/*.md", "outputs/**/*.md", "projects/**/*.md", "areas/**/*.md"]
ROOT_CAP_HINT = 200  # docs/raw-layout.md: 서브폴더 재구조화 재검토 임계
YML_PATH = "docs/raw-index.yml"
MD_PATH = "docs/raw-index.md"
PRIVATE_YML_PATH = "private/raw-index.yml"

# git's default core.quotepath=true octal-escapes every non-ASCII path in
# --name-only output, so Korean/smart-punctuation filenames never matched the
# os.listdir names and were reported as "untracked" on machines with the default
# config (2026-09-03, 34 files). Force quotepath off and normalize to NFC on both sides.
GIT = ["git", "-c", "core.quotepath=false"]


def fail(msg: str) -> None:
    sys.exit(f"generate_raw_index: {msg}")


def nfc(s: str) -> str:
    return unicodedata.normalize("NFC", s)


def first_add_dates() -> dict:
    """First git add date per current raw/*.md path (renames counted as adds)."""
    out = subprocess.run(
        GIT + ["log", "--reverse", "--no-renames", "--diff-filter=A",
               "--name-only", "--format=@%ad", "--date=short", "--", "raw/"],
        capture_output=True, text=True,
    ).stdout
    dates, current = {}, None
    for line in out.splitlines():
        if line.startswith("@"):
            current = line[1:]
        elif line.startswith("raw/") and line.endswith(".md") and "/" not in line[4:]:
            dates.setdefault(nfc(line[4:]), current)
    return dates


def tracked_raw() -> set:
    out = subprocess.run(GIT + ["ls-files", "--", "raw/"], capture_output=True, text=True).stdout
    return {nfc(l[4:]) for l in out.splitlines()
            if l.startswith("raw/") and l.endswith(".md") and "/" not in l[4:]}


def frontmatter_source(path: str) -> str:
    try:
        with open(path, encoding="utf-8") as fh:
            head = fh.read(3000)
    except OSError:
        return ""
    if not head.startswith("---"):
        return ""
    m = re.search(r'^source:\s*"?([^"\n]+?)"?\s*$', head, re.M)
    return m.group(1).strip() if m else ""


def y(s) -> str:
    """YAML scalar: JSON quoting is a valid YAML double-quoted string."""
    return json.dumps(s, ensure_ascii=False)


def emit_entries_yml(entries: list) -> list:
    lines = []
    for e in entries:
        lines.append(f"  - file: {y('raw/' + e['name'])}")
        lines.append(f"    added: {y(e['added'])}")
        lines.append(f"    source: {y(e['source'])}")
        if e["refs"]:
            lines.append("    refs:")
            lines += [f"      - {y(r)}" for r in e["refs"]]
        else:
            lines.append("    refs: []")
    return lines


def main() -> None:
    if not (os.path.isdir("raw") and os.path.isfile("VAULT_RULES.md")):
        fail("run from the vault root (raw/ + VAULT_RULES.md required)")

    raws = sorted((nfc(f) for f in os.listdir("raw") if f.endswith(".md")))
    shots = len(glob.glob("raw/screenshots/**/*.*", recursive=True))

    corpus = {}
    for pattern in SCAN_GLOBS:
        for path in glob.glob(pattern, recursive=True):
            try:
                corpus[path] = open(path, encoding="utf-8").read()
            except OSError:
                pass

    added = first_add_dates()
    tracked = tracked_raw()
    entries, private_entries, sources = [], [], {}
    for name in raws:
        refs = sorted(p for p, text in corpus.items() if f"raw/{name}" in nfc(text))
        src = frontmatter_source(f"raw/{name}")
        entry = {"name": name, "source": src, "refs": refs}
        if name in tracked:
            entry["added"] = added.get(name, "unknown")
            entries.append(entry)
            if src:
                sources.setdefault(src, []).append(name)
        else:
            entry["added"] = "untracked"
            private_entries.append(entry)

    orphans = [e["name"] for e in entries if not e["refs"]]
    dup_urls = {u: fs for u, fs in sources.items()
                if len(fs) > 1 and u.startswith("http")}
    by_month = {}
    for e in entries:
        by_month[e["added"][:7]] = by_month.get(e["added"][:7], 0) + 1

    today = datetime.date.today().isoformat()

    # --- docs/raw-index.yml (canonical) ---
    yml = [
        "# Raw Index — raw/ 보존소의 자동 생성 색인. 수동 편집 금지.",
        "# 재생성: vault 루트에서 python3 projects/second-brain/config/scripts/generate_raw_index.py",
        "# 계약: docs/raw-layout.md § 색인. 사람용 요약: docs/raw-index.md",
        f"generated: {y(today)}",
        f"root_files: {len(entries)}",
        f"root_cap: {ROOT_CAP_HINT}",
        f"screenshots: {shots}",
        "by_month:",
    ]
    yml += [f"  {y(m)}: {n}" for m, n in sorted(by_month.items(), reverse=True)]
    yml.append("orphans:" + (" []" if not orphans else ""))
    yml += [f"  - {y('raw/' + n)}" for n in orphans]
    yml.append("duplicate_sources:" + (" []" if not dup_urls else ""))
    for url, files in sorted(dup_urls.items()):
        yml.append(f"  - url: {y(url)}")
        yml.append("    files:")
        yml += [f"      - {y('raw/' + n)}" for n in files]
    yml.append("entries:")
    yml += emit_entries_yml(sorted(entries, key=lambda e: (e["added"], e["name"]), reverse=True))
    yml.append("")
    with open(YML_PATH, "w", encoding="utf-8") as fh:
        fh.write("\n".join(yml))

    # --- docs/raw-index.md (summary only) ---
    md = [
        "# Raw Index",
        "",
        "`raw/` 보존소의 자동 생성 색인 요약 — **수동 편집 금지.** 파일별 상세(유입일·source·파생 노트 역링크)는",
        f"`{YML_PATH}`에 있다. 재생성: vault 루트에서 `python3 projects/second-brain/config/scripts/generate_raw_index.py`",
        "(`vault-lint` 패스가 실행). 계약: `docs/raw-layout.md` § 색인.",
        "",
        f"- 생성: {today} · 루트 파일 {len(entries)} (서브폴더 재구조화 임계 {ROOT_CAP_HINT})"
        f" · screenshots 레인 {shots}개 항목",
        f"- 오펀(참조 0건): {len(orphans)} · source URL 중복: {len(dup_urls)}",
        "- 월별 유입: " + " · ".join(f"{m} {n}" for m, n in sorted(by_month.items(), reverse=True)),
    ]
    if orphans:
        md += ["", "## 오펀 — lint 리포트 대상", ""]
        md += [f"- `raw/{n}`" for n in orphans]
    if dup_urls:
        md += ["", "## source URL 중복 — lint 리포트 대상", ""]
        for url, files in sorted(dup_urls.items()):
            md.append(f"- {url}")
            md += [f"  - `raw/{n}`" for n in files]
    md.append("")
    with open(MD_PATH, "w", encoding="utf-8") as fh:
        fh.write("\n".join(md))

    # --- private/raw-index.yml (this machine's untracked raw files only) ---
    if private_entries:
        os.makedirs("private", exist_ok=True)
        pv = [
            "# 이 머신에서 git이 추적하지 않는 raw/*.md — 개인/로컬 파일. private/는 gitignored.",
            "# generate_raw_index.py가 재생성한다. 공유 색인(docs/raw-index.yml)에는 실리지 않는다.",
            f"generated: {y(today)}",
            f"untracked_files: {len(private_entries)}",
            "entries:",
        ]
        pv += emit_entries_yml(private_entries)
        pv.append("")
        with open(PRIVATE_YML_PATH, "w", encoding="utf-8") as fh:
            fh.write("\n".join(pv))
    elif os.path.isfile(PRIVATE_YML_PATH):
        os.remove(PRIVATE_YML_PATH)

    print(f"{YML_PATH} + {MD_PATH} written: {len(entries)} tracked files, "
          f"{len(orphans)} orphans, {len(dup_urls)} duplicate URLs"
          + (f"; {len(private_entries)} untracked → {PRIVATE_YML_PATH}" if private_entries else ""))


if __name__ == "__main__":
    main()
